version: "3.7"
services:
  app:
    build: .
    ports:
      - "3000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: [ './start.sh' ]

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - "app"

  db:
    image: mysql:8.0.21
    ports:
      - "13306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_conf/:/etc/mysql/conf.d
    environment:
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE_NAME: "${DB_USER}"
      TZ: 'Asia/Tokyo'

  minio:
    image: minio/minio:latest
    ports:
      - "9090:9000"
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
    entrypoint: sh
    command: -c "mkdir -p /data/.minio.sys/buckets; cp -r /policies/* /data/.minio.sys/; cp -r /export/* /data/; /usr/bin/minio server /data;"
    volumes:
      - minio:/data:cached
      - ./docker/minio/export:/export
      - ./docker/minio/policies:/policies

volumes:
  app:
  db:
  minio:
