version: "3.7"
services:
  app:
    build: .
    ports:
      - "3030:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: ['./start.sh']

  db:
    image: mysql:8.0.21
    ports:
      - "13306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
      - ./db/mysql_conf/:/etc/mysql/conf.d
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'trout_analyzer'
      TZ: 'Asia/Tokyo'